import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { studentAPI, tripAPI, meetingAPI, adminAPI, paymentAPI } from '../../services/api';
import logo from '../../assets/logo.svg';

// ─── Utilities ───────────────────────────────────────────────────────────────

const monthStart = () => { const d = new Date(); d.setDate(1); return d.toISOString().split('T')[0]; };
const todayStr  = () => new Date().toISOString().split('T')[0];

const exportCSV = (rows, filename) => {
    if (!rows.length) return;
    const keys = Object.keys(rows[0]);
    const lines = [
        keys.join(','),
        ...rows.map(r => keys.map(k => {
            const v = String(r[k] ?? '').replace(/"/g, '""');
            return /[,"\n\r]/.test(v) ? `"${v}"` : v;
        }).join(','))
    ];
    const blob = new Blob([lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' });
    const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: filename });
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
};

const fmtDate = (v) => {
    if (!v) return '—';
    try { return new Date(v?._seconds ? v._seconds * 1000 : v).toLocaleDateString('en-ZA'); }
    catch { return '—'; }
};

const fmtDateTime = (v) => {
    if (!v) return '—';
    try { return new Date(v?._seconds ? v._seconds * 1000 : v).toLocaleString('en-ZA'); }
    catch { return '—'; }
};

const inRange = (dateVal, from, to) => {
    if (!dateVal) return true;
    try {
        const d = new Date(dateVal?._seconds ? dateVal._seconds * 1000 : dateVal);
        if (isNaN(d)) return true;
        if (from && d < new Date(from)) return false;
        if (to   && d > new Date(to + 'T23:59:59')) return false;
        return true;
    } catch { return true; }
};

// ─── Shared Components ───────────────────────────────────────────────────────

const PrintHeader = ({ title, user, dateFrom, dateTo }) => (
    <div className="print-only">
        <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 12 }}>
            <img src={logo} alt="MHS" style={{ width: 56, height: 56 }} />
            <div>
                <div style={{ fontSize: 20, fontWeight: 800, color: '#0B1F4A' }}>Meridian High School High School</div>
                <div style={{ fontSize: 12, color: '#666' }}>Official Management Report</div>
            </div>
        </div>
        <div style={{ borderTop: '3px solid #C8A94A', paddingTop: 10, marginBottom: 14 }}>
            <div style={{ fontSize: 16, fontWeight: 700, color: '#0B1F4A' }}>{title}</div>
            <div style={{ fontSize: 11, color: '#555', marginTop: 4 }}>
                Generated by: <strong>{user?.fullName}</strong> ({user?.role}) &nbsp;|&nbsp;
                Period: {dateFrom && dateTo ? `${dateFrom} – ${dateTo}` : dateFrom ? `From ${dateFrom}` : dateTo ? `Up to ${dateTo}` : 'All dates'} &nbsp;|&nbsp;
                Printed: {new Date().toLocaleString('en-ZA')}
            </div>
        </div>
    </div>
);

const ReportFilters = ({ dateFrom, dateTo, setDateFrom, setDateTo, onCSV, onPrint, children }) => (
    <div className="report-filters no-print">
        <div className="report-filter-row">
            <div className="report-filter-group">
                <label>Date From <span style={{ fontWeight: 400, textTransform: 'none', fontSize: '10px', opacity: 0.7 }}>(optional)</span></label>
                <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} />
            </div>
            <div className="report-filter-group">
                <label>Date To <span style={{ fontWeight: 400, textTransform: 'none', fontSize: '10px', opacity: 0.7 }}>(optional)</span></label>
                <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} />
            </div>
            {children}
            <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'flex-end' }}>
                <button className="btn-report-csv" onClick={onCSV}>⬇ Export CSV</button>
                <button className="btn-report-pdf" onClick={onPrint}>🖨 Print / PDF</button>
            </div>
        </div>
    </div>
);

const ReportMeta = ({ title, user, count, dateFrom, dateTo }) => (
    <div className="report-meta-bar no-print">
        <span className="report-meta-title">{title}</span>
        <span className="report-meta-info">
            Admin: <strong>{user?.fullName}</strong> &nbsp;·&nbsp;
            {dateFrom || dateTo
                ? <>{dateFrom || '…'} – {dateTo || '…'}</>
                : <em>All dates</em>}
            &nbsp;·&nbsp; <strong>{count}</strong> record{count !== 1 ? 's' : ''}
        </span>
    </div>
);

// ─── 1. Summary Report ───────────────────────────────────────────────────────

const SummaryReport = ({ user }) => {
    const [data, setData] = useState({ students: [], trips: [], meetings: [], announcements: [] });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        Promise.all([
            studentAPI.getAllStudents(),
            tripAPI.getAllTrips(),
            meetingAPI.getAllMeetings(),
            adminAPI.getAllAnnouncements(),
        ]).then(([s, t, m, a]) => {
            setData({
                students:      s.data.data || [],
                trips:         t.data.data || [],
                meetings:      m.data.data || [],
                announcements: a.data.data || [],
            });
        }).catch(console.error).finally(() => setLoading(false));
    }, []);

    if (loading) return <div className="loading">Loading summary…</div>;

    const { students, trips, meetings, announcements } = data;
    const approved  = students.filter(s => s.status === 'APPROVED').length;
    const pending   = students.filter(s => s.status === 'PENDING').length;
    const rejected  = students.filter(s => s.status === 'REJECTED').length;
    const activeTr  = trips.filter(t => t.status === 'ACTIVE').length;
    const pendingM  = meetings.filter(m => m.status === 'PENDING').length;
    const approvedM = meetings.filter(m => m.status === 'APPROVED' || m.status === 'SCHEDULED').length;

    const gradeBreakdown = {};
    students.filter(s => s.status === 'APPROVED').forEach(s => {
        const g = s.grade || 'Unknown';
        gradeBreakdown[g] = (gradeBreakdown[g] || 0) + 1;
    });

    const announcementBreakdown = {};
    announcements.forEach(a => {
        announcementBreakdown[a.type] = (announcementBreakdown[a.type] || 0) + 1;
    });

    const handlePrint = () => window.print();
    const handleCSV = () => exportCSV([
        { Category: 'Total Students',          Value: students.length },
        { Category: 'Approved Students',        Value: approved },
        { Category: 'Pending Applications',     Value: pending },
        { Category: 'Rejected Applications',    Value: rejected },
        { Category: 'Total Trips',              Value: trips.length },
        { Category: 'Active Trips',             Value: activeTr },
        { Category: 'Total Meetings',           Value: meetings.length },
        { Category: 'Pending Meetings',         Value: pendingM },
        { Category: 'Approved Meetings',        Value: approvedM },
        { Category: 'Total Announcements',      Value: announcements.length },
    ], `MHS_Summary_Report_${todayStr()}.csv`);

    return (
        <div className="print-area">
            <PrintHeader title="Management Summary Report" user={user} dateFrom="—" dateTo={todayStr()} />

            <div className="no-print" style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginBottom: 16 }}>
                <button className="btn-report-csv" onClick={handleCSV}>⬇ Export CSV</button>
                <button className="btn-report-pdf" onClick={handlePrint}>🖨 Print / PDF</button>
            </div>

            <div className="summary-report-grid">
                <div className="summary-report-card">
                    <div className="src-label">Total Students</div>
                    <div className="src-value">{students.length}</div>
                    <div className="src-breakdown">
                        <span className="src-pill green">{approved} Enrolled</span>
                        <span className="src-pill amber">{pending} Pending</span>
                        <span className="src-pill red">{rejected} Rejected</span>
                    </div>
                </div>
                <div className="summary-report-card">
                    <div className="src-label">School Trips</div>
                    <div className="src-value">{trips.length}</div>
                    <div className="src-breakdown">
                        <span className="src-pill green">{activeTr} Active</span>
                        <span className="src-pill amber">{trips.length - activeTr} On Hold</span>
                    </div>
                </div>
                <div className="summary-report-card">
                    <div className="src-label">Meetings</div>
                    <div className="src-value">{meetings.length}</div>
                    <div className="src-breakdown">
                        <span className="src-pill amber">{pendingM} Pending</span>
                        <span className="src-pill green">{approvedM} Approved</span>
                    </div>
                </div>
                <div className="summary-report-card">
                    <div className="src-label">Announcements</div>
                    <div className="src-value">{announcements.length}</div>
                    <div className="src-breakdown">
                        {Object.entries(announcementBreakdown).map(([type, cnt]) => (
                            <span key={type} className="src-pill blue">{cnt} {type}</span>
                        ))}
                    </div>
                </div>
            </div>

            <div className="report-section-title">Student Enrolment by Grade</div>
            <table className="report-table">
                <thead><tr><th>Grade</th><th>Enrolled Students</th></tr></thead>
                <tbody>
                    {Object.entries(gradeBreakdown).sort().map(([grade, count]) => (
                        <tr key={grade}><td>{grade}</td><td>{count}</td></tr>
                    ))}
                    <tr className="report-table-total">
                        <td><strong>Total</strong></td>
                        <td><strong>{approved}</strong></td>
                    </tr>
                </tbody>
            </table>

            <div className="report-section-title">Announcement Breakdown by Type</div>
            <table className="report-table">
                <thead><tr><th>Type</th><th>Count</th></tr></thead>
                <tbody>
                    {Object.entries(announcementBreakdown).map(([type, cnt]) => (
                        <tr key={type}><td>{type}</td><td>{cnt}</td></tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

// ─── 2. Student Enrolment Report ─────────────────────────────────────────────

const StudentReport = ({ user }) => {
    const [allStudents, setAllStudents] = useState([]);
    const [loading, setLoading] = useState(true);
    const [dateFrom, setDateFrom] = useState('');
    const [dateTo, setDateTo] = useState('');
    const [statusFilter, setStatusFilter] = useState('ALL');
    const [gradeFilter, setGradeFilter] = useState('ALL');

    useEffect(() => {
        studentAPI.getAllStudents()
            .then(r => setAllStudents(r.data.data || []))
            .catch(console.error)
            .finally(() => setLoading(false));
    }, []);

    if (loading) return <div className="loading">Loading students…</div>;

    const grades = [...new Set(allStudents.map(s => s.grade).filter(Boolean))].sort();

    const filtered = allStudents.filter(s => {
        if (statusFilter !== 'ALL' && s.status !== statusFilter) return false;
        if (gradeFilter  !== 'ALL' && s.grade  !== gradeFilter)  return false;
        const dateField = s.createdAt || s.admissionYear;
        if (dateField && !inRange(dateField, dateFrom, dateTo)) return false;
        return true;
    });

    const csvRows = filtered.map(s => ({
        'Student Name':   `${s.name || ''} ${s.surname || ''}`.trim(),
        'Grade':          s.grade || '—',
        'Gender':         s.gender || '—',
        'Date of Birth':  fmtDate(s.dateOfBirth),
        'Nationality':    s.nationality || '—',
        'Admission Year': s.admissionYear || '—',
        'Status':         s.status || '—',
        'Parent Name':    s.parentName || '—',
        'Parent ID':      s.parentId || '—',
    }));

    return (
        <div className="print-area">
            <PrintHeader title="Student Enrolment Report" user={user} dateFrom={dateFrom} dateTo={dateTo} />
            <ReportFilters dateFrom={dateFrom} dateTo={dateTo}
                setDateFrom={setDateFrom} setDateTo={setDateTo}
                onCSV={() => exportCSV(csvRows, `MHS_Students_Report_${todayStr()}.csv`)}
                onPrint={() => window.print()}>
                <div className="report-filter-group">
                    <label>Status</label>
                    <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
                        <option value="ALL">All Statuses</option>
                        <option value="APPROVED">Approved</option>
                        <option value="PENDING">Pending</option>
                        <option value="REJECTED">Rejected</option>
                    </select>
                </div>
                <div className="report-filter-group">
                    <label>Grade</label>
                    <select value={gradeFilter} onChange={e => setGradeFilter(e.target.value)}>
                        <option value="ALL">All Grades</option>
                        {grades.map(g => <option key={g} value={g}>{g}</option>)}
                    </select>
                </div>
            </ReportFilters>
            <ReportMeta title="Student Enrolment Report" user={user} count={filtered.length} dateFrom={dateFrom} dateTo={dateTo} />
            <table className="report-table">
                <thead>
                    <tr>
                        <th>#</th><th>Student Name</th><th>Grade</th><th>Gender</th>
                        <th>Date of Birth</th><th>Nationality</th><th>Admission Year</th>
                        <th>Parent / Guardian</th><th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {filtered.length === 0 ? (
                        <tr><td colSpan="9" style={{ textAlign: 'center', padding: 32, color: 'var(--text-muted)' }}>No records match the selected filters.</td></tr>
                    ) : filtered.map((s, i) => (
                        <tr key={s.studentId || i}>
                            <td>{i + 1}</td>
                            <td><strong>{s.name} {s.surname}</strong></td>
                            <td>{s.grade || '—'}</td>
                            <td>{s.gender || '—'}</td>
                            <td>{fmtDate(s.dateOfBirth)}</td>
                            <td>{s.nationality || '—'}</td>
                            <td>{s.admissionYear || '—'}</td>
                            <td>{s.parentName || '—'}</td>
                            <td>
                                <span className={`badge badge-${s.status === 'APPROVED' ? 'success' : s.status === 'PENDING' ? 'warning' : 'danger'}`}>
                                    {s.status}
                                </span>
                            </td>
                        </tr>
                    ))}
                </tbody>
                {filtered.length > 0 && (
                    <tfoot>
                        <tr className="report-table-total">
                            <td colSpan="8"><strong>Total Records</strong></td>
                            <td><strong>{filtered.length}</strong></td>
                        </tr>
                    </tfoot>
                )}
            </table>
        </div>
    );
};

// ─── 3. Trip Registration Report ─────────────────────────────────────────────

const TripReport = ({ user }) => {
    const [allTrips, setAllTrips] = useState([]);
    const [allPayments, setAllPayments] = useState([]);
    const [loading, setLoading] = useState(true);
    const [dateFrom, setDateFrom] = useState('');
    const [dateTo, setDateTo] = useState('');
    const [statusFilter, setStatusFilter] = useState('ALL');

    useEffect(() => {
        Promise.all([tripAPI.getAllTrips(), paymentAPI.getAllPayments()])
            .then(([t, p]) => {
                setAllTrips(t.data.data || []);
                setAllPayments(p.data.data || []);
            })
            .catch(console.error)
            .finally(() => setLoading(false));
    }, []);

    if (loading) return <div className="loading">Loading trips…</div>;

    const filtered = allTrips.filter(t => {
        if (statusFilter !== 'ALL' && t.status !== statusFilter) return false;
        return inRange(t.tripDate, dateFrom, dateTo);
    });

    const enriched = filtered.map(t => {
        const tripPayments = allPayments.filter(p => p.tripId === t.tripId || p.tripId === String(t.tripId));
        const paid = tripPayments.filter(p => p.status === 'COMPLETED' || p.status === 'PAID').length;
        const revenue = paid * (t.price || 0);
        return { ...t, registrations: tripPayments.length, paidCount: paid, revenue };
    });

    const csvRows = enriched.map(t => ({
        'Trip Title':      t.title,
        'Destination':     t.destination || '—',
        'Trip Date':       fmtDate(t.tripDate),
        'Price (R)':       t.price || 0,
        'Status':          t.status || '—',
        'Eligible Grades': (t.eligibleGrades || []).join(', '),
        'Registrations':   t.registrations,
        'Paid':            t.paidCount,
        'Revenue (R)':     t.revenue.toFixed(2),
    }));

    const totalRevenue = enriched.reduce((sum, t) => sum + (t.revenue || 0), 0);

    return (
        <div className="print-area">
            <PrintHeader title="Trip Registration Report" user={user} dateFrom={dateFrom} dateTo={dateTo} />
            <ReportFilters dateFrom={dateFrom} dateTo={dateTo}
                setDateFrom={setDateFrom} setDateTo={setDateTo}
                onCSV={() => exportCSV(csvRows, `MHS_Trips_Report_${todayStr()}.csv`)}
                onPrint={() => window.print()}>
                <div className="report-filter-group">
                    <label>Status</label>
                    <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
                        <option value="ALL">All</option>
                        <option value="ACTIVE">Active</option>
                        <option value="ON_HOLD">On Hold</option>
                        <option value="CANCELLED">Cancelled</option>
                    </select>
                </div>
            </ReportFilters>
            <ReportMeta title="Trip Registration Report" user={user} count={filtered.length} dateFrom={dateFrom} dateTo={dateTo} />
            <table className="report-table">
                <thead>
                    <tr>
                        <th>#</th><th>Trip Title</th><th>Destination</th><th>Trip Date</th>
                        <th>Price (R)</th><th>Eligible Grades</th>
                        <th>Registrations</th><th>Paid</th><th>Revenue (R)</th><th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {enriched.length === 0 ? (
                        <tr><td colSpan="10" style={{ textAlign: 'center', padding: 32, color: 'var(--text-muted)' }}>No trips found for selected filters.</td></tr>
                    ) : enriched.map((t, i) => (
                        <tr key={t.tripId || i}>
                            <td>{i + 1}</td>
                            <td><strong>{t.title}</strong></td>
                            <td>{t.destination || '—'}</td>
                            <td>{fmtDate(t.tripDate)}</td>
                            <td>R {(t.price || 0).toFixed(2)}</td>
                            <td>{(t.eligibleGrades || []).join(', ') || '—'}</td>
                            <td>{t.registrations}</td>
                            <td>{t.paidCount}</td>
                            <td>R {t.revenue.toFixed(2)}</td>
                            <td><span className={`badge badge-${t.status === 'ACTIVE' ? 'success' : 'warning'}`}>{t.status}</span></td>
                        </tr>
                    ))}
                </tbody>
                {enriched.length > 0 && (
                    <tfoot>
                        <tr className="report-table-total">
                            <td colSpan="8"><strong>Total Revenue</strong></td>
                            <td><strong>R {totalRevenue.toFixed(2)}</strong></td>
                            <td></td>
                        </tr>
                    </tfoot>
                )}
            </table>
        </div>
    );
};

// ─── 4. Meeting Activity Report ───────────────────────────────────────────────

const MeetingReport = ({ user }) => {
    const [allMeetings, setAllMeetings] = useState([]);
    const [loading, setLoading] = useState(true);
    const [dateFrom, setDateFrom] = useState('');
    const [dateTo, setDateTo] = useState('');
    const [statusFilter, setStatusFilter] = useState('ALL');
    const [typeFilter, setTypeFilter] = useState('ALL');

    useEffect(() => {
        meetingAPI.getAllMeetings()
            .then(r => setAllMeetings(r.data.data || []))
            .catch(console.error)
            .finally(() => setLoading(false));
    }, []);

    if (loading) return <div className="loading">Loading meetings…</div>;

    const filtered = allMeetings.filter(m => {
        if (statusFilter !== 'ALL' && m.status !== statusFilter) return false;
        if (typeFilter   !== 'ALL' && m.type   !== typeFilter)   return false;
        return inRange(m.scheduledTime, dateFrom, dateTo);
    });

    const csvRows = filtered.map(m => ({
        'Title':          m.title || '—',
        'Type':           (m.type || '').replace('_', ' '),
        'Teacher':        m.teacherName || '—',
        'Scheduled Time': fmtDateTime(m.scheduledTime),
        'Requested By':   m.parentName || '—',
        'Status':         m.status || '—',
        'Description':    m.description || '—',
        'Rejection Reason': m.rejectionReason || '—',
    }));

    const statusBreakdown = {};
    filtered.forEach(m => { statusBreakdown[m.status] = (statusBreakdown[m.status] || 0) + 1; });

    return (
        <div className="print-area">
            <PrintHeader title="Meeting Activity Report" user={user} dateFrom={dateFrom} dateTo={dateTo} />
            <ReportFilters dateFrom={dateFrom} dateTo={dateTo}
                setDateFrom={setDateFrom} setDateTo={setDateTo}
                onCSV={() => exportCSV(csvRows, `MHS_Meetings_Report_${todayStr()}.csv`)}
                onPrint={() => window.print()}>
                <div className="report-filter-group">
                    <label>Status</label>
                    <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
                        <option value="ALL">All Statuses</option>
                        <option value="PENDING">Pending</option>
                        <option value="APPROVED">Approved</option>
                        <option value="SCHEDULED">Scheduled</option>
                        <option value="REJECTED">Rejected</option>
                        <option value="COMPLETED">Completed</option>
                    </select>
                </div>
                <div className="report-filter-group">
                    <label>Type</label>
                    <select value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
                        <option value="ALL">All Types</option>
                        <option value="GROUP_MEETING">Group Meeting</option>
                        <option value="ONE_ON_ONE">One-on-One</option>
                    </select>
                </div>
            </ReportFilters>
            <ReportMeta title="Meeting Activity Report" user={user} count={filtered.length} dateFrom={dateFrom} dateTo={dateTo} />

            <div className="report-status-summary no-print">
                {Object.entries(statusBreakdown).map(([status, cnt]) => (
                    <div key={status} className="rss-item">
                        <span className={`badge badge-${status === 'APPROVED' || status === 'SCHEDULED' ? 'success' : status === 'PENDING' ? 'warning' : status === 'REJECTED' ? 'danger' : 'muted'}`}>{status}</span>
                        <strong>{cnt}</strong>
                    </div>
                ))}
            </div>

            <table className="report-table">
                <thead>
                    <tr>
                        <th>#</th><th>Meeting Title</th><th>Type</th><th>Teacher</th>
                        <th>Scheduled Time</th><th>Requested By</th><th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {filtered.length === 0 ? (
                        <tr><td colSpan="7" style={{ textAlign: 'center', padding: 32, color: 'var(--text-muted)' }}>No meetings found for selected filters.</td></tr>
                    ) : filtered.map((m, i) => (
                        <tr key={m.meetingId || i}>
                            <td>{i + 1}</td>
                            <td>
                                <strong>{m.title}</strong>
                                {m.description && <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>{m.description.slice(0, 60)}{m.description.length > 60 ? '…' : ''}</div>}
                            </td>
                            <td style={{ fontSize: 12 }}>{(m.type || '').replace('_', ' ')}</td>
                            <td>{m.teacherName || '—'}</td>
                            <td style={{ fontSize: 12, whiteSpace: 'nowrap' }}>{fmtDateTime(m.scheduledTime)}</td>
                            <td>{m.parentName || '—'}</td>
                            <td>
                                <span className={`badge badge-${m.status === 'APPROVED' || m.status === 'SCHEDULED' ? 'success' : m.status === 'PENDING' ? 'warning' : m.status === 'REJECTED' ? 'danger' : 'muted'}`}>
                                    {m.status}
                                </span>
                            </td>
                        </tr>
                    ))}
                </tbody>
                {filtered.length > 0 && (
                    <tfoot>
                        <tr className="report-table-total">
                            <td colSpan="6"><strong>Total Meetings</strong></td>
                            <td><strong>{filtered.length}</strong></td>
                        </tr>
                    </tfoot>
                )}
            </table>
        </div>
    );
};

// ─── 5. Announcement Report ───────────────────────────────────────────────────

const AnnouncementReport = ({ user }) => {
    const [all, setAll] = useState([]);
    const [loading, setLoading] = useState(true);
    const [dateFrom, setDateFrom] = useState('');
    const [dateTo, setDateTo] = useState('');
    const [typeFilter, setTypeFilter] = useState('ALL');

    useEffect(() => {
        adminAPI.getAllAnnouncements()
            .then(r => setAll(r.data.data || []))
            .catch(console.error)
            .finally(() => setLoading(false));
    }, []);

    if (loading) return <div className="loading">Loading announcements…</div>;

    const filtered = all.filter(a => {
        if (typeFilter !== 'ALL' && a.type !== typeFilter) return false;
        return inRange(a.createdAt, dateFrom, dateTo);
    });

    const csvRows = filtered.map(a => ({
        'Title':       a.title || '—',
        'Type':        a.type || '—',
        'Content':     a.content || '—',
        'Published':   fmtDate(a.createdAt),
        'Admin':       user?.fullName || '—',
    }));

    const typeBreakdown = {};
    filtered.forEach(a => { typeBreakdown[a.type] = (typeBreakdown[a.type] || 0) + 1; });

    const TYPE_COLORS = {
        URGENT:  { bg: '#fee2e2', color: '#991b1b' },
        EXAM:    { bg: '#fef3c7', color: '#92400e' },
        HOLIDAY: { bg: '#d1fae5', color: '#065f46' },
        GENERAL: { bg: '#e0f2fe', color: '#075985' },
    };

    return (
        <div className="print-area">
            <PrintHeader title="Announcement Report" user={user} dateFrom={dateFrom} dateTo={dateTo} />
            <ReportFilters dateFrom={dateFrom} dateTo={dateTo}
                setDateFrom={setDateFrom} setDateTo={setDateTo}
                onCSV={() => exportCSV(csvRows, `MHS_Announcements_Report_${todayStr()}.csv`)}
                onPrint={() => window.print()}>
                <div className="report-filter-group">
                    <label>Type</label>
                    <select value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
                        <option value="ALL">All Types</option>
                        <option value="GENERAL">General</option>
                        <option value="URGENT">Urgent</option>
                        <option value="EXAM">Exam</option>
                        <option value="HOLIDAY">Holiday</option>
                    </select>
                </div>
            </ReportFilters>
            <ReportMeta title="Announcement Report" user={user} count={filtered.length} dateFrom={dateFrom} dateTo={dateTo} />

            <div className="report-status-summary no-print">
                {Object.entries(typeBreakdown).map(([type, cnt]) => {
                    const c = TYPE_COLORS[type] || TYPE_COLORS.GENERAL;
                    return (
                        <div key={type} className="rss-item">
                            <span className="badge" style={{ background: c.bg, color: c.color }}>{type}</span>
                            <strong>{cnt}</strong>
                        </div>
                    );
                })}
            </div>

            <table className="report-table">
                <thead>
                    <tr><th>#</th><th>Title</th><th>Type</th><th>Content</th><th>Published By</th><th>Date Published</th></tr>
                </thead>
                <tbody>
                    {filtered.length === 0 ? (
                        <tr><td colSpan="6" style={{ textAlign: 'center', padding: 32, color: 'var(--text-muted)' }}>No announcements found.</td></tr>
                    ) : filtered.map((a, i) => {
                        const c = TYPE_COLORS[a.type] || TYPE_COLORS.GENERAL;
                        return (
                            <tr key={a.announcementId || i}>
                                <td>{i + 1}</td>
                                <td><strong>{a.title}</strong></td>
                                <td><span className="badge" style={{ background: c.bg, color: c.color }}>{a.type}</span></td>
                                <td style={{ fontSize: 12, color: 'var(--text-muted)', maxWidth: 360 }}>
                                    {a.content?.slice(0, 120)}{a.content?.length > 120 ? '…' : ''}
                                </td>
                                <td>{user?.fullName || '—'}</td>
                                <td style={{ whiteSpace: 'nowrap', fontSize: 12 }}>{fmtDate(a.createdAt)}</td>
                            </tr>
                        );
                    })}
                </tbody>
                {filtered.length > 0 && (
                    <tfoot>
                        <tr className="report-table-total">
                            <td colSpan="5"><strong>Total</strong></td>
                            <td><strong>{filtered.length}</strong></td>
                        </tr>
                    </tfoot>
                )}
            </table>
        </div>
    );
};

// ─── Main Reports Page ────────────────────────────────────────────────────────

const TABS = [
    { id: 'summary',       label: '📊 Summary',       desc: 'Management overview' },
    { id: 'students',      label: '🎓 Students',       desc: 'Enrolment report' },
    { id: 'trips',         label: '🚌 Trips',          desc: 'Trip registrations' },
    { id: 'meetings',      label: '📅 Meetings',       desc: 'Meeting activity' },
    { id: 'announcements', label: '📢 Announcements',  desc: 'Published announcements' },
];

const Reports = () => {
    const { user } = useAuth();
    const [activeTab, setActiveTab] = useState('summary');

    return (
        <div className="page-wrapper">
            <div className="page-header no-print">
                <div>
                    <h1 className="page-title">Reports</h1>
                    <p className="page-subtitle">Management reports with filters and export for Meridian High School</p>
                </div>
            </div>

            <div className="report-tab-bar no-print">
                {TABS.map(t => (
                    <button
                        key={t.id}
                        className={`report-tab${activeTab === t.id ? ' active' : ''}`}
                        onClick={() => setActiveTab(t.id)}
                    >
                        <span className="report-tab-label">{t.label}</span>
                        <span className="report-tab-desc">{t.desc}</span>
                    </button>
                ))}
            </div>

            <div className="report-body">
                {activeTab === 'summary'       && <SummaryReport       user={user} />}
                {activeTab === 'students'      && <StudentReport       user={user} />}
                {activeTab === 'trips'         && <TripReport          user={user} />}
                {activeTab === 'meetings'      && <MeetingReport       user={user} />}
                {activeTab === 'announcements' && <AnnouncementReport  user={user} />}
            </div>
        </div>
    );
};

export default Reports;
